In [12]:
sales.shape

(117601, 30)

In [11]:
sales.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_height_cm,product_width_cm,payment_sequential,payment_type,payment_installments,payment_value,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,8.0,13.0,1,credit_card,1,18.12,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,8.0,13.0,3,voucher,1,2.00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,8.0,13.0,2,voucher,1,18.59,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,...,13.0,19.0,1,boleto,1,141.46,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,...,19.0,21.0,1,credit_card,3,179.12,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO

In [10]:
sales = (
    orders
    .merge(order_items, on="order_id")
    .merge(products, on="product_id")
    .merge(payments, on="order_id")
    .merge(customers, on="customer_id")
)

In [9]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB

In [8]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [7]:
duplicate_summary = pd.DataFrame({
    "Table": tables.keys(),
    "Duplicate Rows": [df.duplicated().sum() for df in tables.values()]
})

duplicate_summary

         Table  Duplicate Rows
0    Customers               0
1       Orders               0
2  Order Items               0
3     Products               0
4     Payments               0
5      Reviews               0
6      Sellers               0
7  Geolocation          261836
8  Translation               0

In [6]:
tables = {
    "Customers": customers,
    "Orders": orders,
    "Order Items": order_items,
    "Products": products,
    "Payments": payments,
    "Reviews": reviews,
    "Sellers": sellers,
    "Geolocation": geolocation,
    "Translation": translation
}

missing_values = pd.DataFrame()

for name, df in tables.items():
    missing = df.isnull().sum()
    missing = missing[missing > 0]

    if not missing.empty:
        temp = pd.DataFrame({
            "Column": missing.index,
            "Missing Values": missing.values
        })
        temp["Table"] = name
        missing_values = pd.concat([missing_values, temp], ignore_index=True)

missing_values

                           Column  Missing Values     Table
0               order_approved_at             160    Orders
1    order_delivered_carrier_date            1783    Orders
2   order_delivered_customer_date            2965    Orders
3           product_category_name             610  Products
4             product_name_lenght             610  Products
5      product_description_lenght             610  Products
6              product_photos_qty             610  Products
7                product_weight_g               2  Products
8               product_length_cm               2  Products
9               product_height_cm               2  Products
10               product_width_cm               2  Products
11           review_comment_title           87656   Reviews
12         review_comment_message           58247   Reviews

In [5]:
print(customers.shape)

(99441, 5)

In [4]:
customers = pd.read_sql("SELECT * FROM customers", engine)
orders = pd.read_sql("SELECT * FROM orders", engine)
order_items = pd.read_sql("SELECT * FROM order_items", engine)
products = pd.read_sql("SELECT * FROM products", engine)
payments = pd.read_sql("SELECT * FROM order_payments", engine)
reviews = pd.read_sql("SELECT * FROM order_reviews", engine)
sellers = pd.read_sql("SELECT * FROM sellers", engine)
geolocation = pd.read_sql("SELECT * FROM geolocation", engine)
translation = pd.read_sql(
    "SELECT * FROM product_category_translation",
    engine
)

In [3]:
with engine.connect() as conn:
    print("Connected Successfully!")

Connected Successfully!

In [2]:
USERNAME = "postgres"
PASSWORD = "password"
HOST = "localhost"
PORT = "5432"
DATABASE = "olist_retail"

engine = create_engine(
    f"postgresql+psycopg2://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
)

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [7]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:password@localhost:5432/olist_retail"
)

with engine.connect() as conn:
    print("Connected Successfully!")

Connected Successfully!

In [6]:
USERNAME = "postgres"
PASSWORD = "password"
HOST = "localhost"
PORT = "5432"
DATABASE = "olist_retail"

engine = create_engine(
    f"postgresql+psycopg2://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
)

In [4]:
USERNAME = "postgres"
PASSWORD = "YOUR_PASSWORD"

HOST = "localhost"
PORT = "5432"
DATABASE = "olist_retail"

engine = create_engine(
    f"postgresql+psycopg2://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
)

In [3]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine

In [2]:
# Data Cleaning

## Objective

# The objective of this notebook is to assess and improve the quality of the Olist Retail dataset before analysis.

# ### Tasks Performed
# - Check missing values
# - Check duplicate records
# - Verify data types
# - Convert date columns
# - Create a master dataset for analysis